solutions 06-events-practice
js-tasks-ru/js-20210615_v-santalau pull request #5
Opened 2021-07-04 23:22 UTC by VitaliSantalau

sortable table V2
tooltip

2021-07-04 23:23 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-07-05 19:53 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +      'pointerdown': event => {
как будет масштабироваться данный подход если в компоненте будет несколько обработчиков `pointerdown`?

2021-07-05 19:54 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +        if (!target) return;
good 👍

2021-07-05 19:54 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +    if (Tooltip.instance) return Tooltip.instance;
good 👍

2021-07-05 19:59 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +        this.element.style.left = `${event.clientX + 5}px`;
значение 5 было бы неплохо вынести в переменную

2021-07-05 20:05 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +        document.removeEventListener('pointermove', this.getHandler('pointermove'));
проверьте пожалуйста, а удаляются ли обработчики событий...
подсказка:
```
    const getFunction = fnName => {
      const obj = {
        foo: () => {
          console.error('foo');
        }
      };

      return obj[fnName];
    };

    const foo1 = getFunction('foo');
    const foo2 = getFunction('foo');

    console.error('foo1', foo1);
    console.error('foo2', foo2);

    console.error(foo1 === foo2);
```

2021-07-05 20:05 UTC, dosandk requested changes
нужно ответить на вопросы, а также проверить обработчики событий в `Tooltip` компоненте

2021-07-05 22:08 UTC, VitaliSantalau commented on 06-events-practice/1-sortable-table-v2/index.js
> +      'pointerdown': event => {
в случае необходимости масштабирования, можно назначать имя свойства объекта более конкретно - "pointerdownFieldHeader"

2021-07-05 22:13 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-07-05 22:19 UTC, VitaliSantalau commented on 06-events-practice/1-sortable-table-v2/index.js
> +      const target = event.target.closest('div[data-sortable]');
конкретизированное имя свойства объекта

2021-07-05 22:25 UTC, VitaliSantalau commented on 06-events-practice/2-tooltip/index.js
> +      this.element.style.top = `${event.clientY + offset}px`;
значение смещение toolltip от указателя мышки, перенез в переменную

2021-07-05 22:32 UTC, VitaliSantalau commented on 06-events-practice/2-tooltip/index.js
> +        document.removeEventListener('pointermove', this.getHandler('pointermove'));
не удалятся, спасибо за подсказку. переделал решение

2021-07-05 22:38 UTC, VitaliSantalau commented on 06-events-practice/2-tooltip/index.js
> +        document.addEventListener('pointermove', this.handlerEvent.pointermove);
функция обработчик сохранена => обработчик события может быть назначен и **удален**

2021-07-05 22:47 UTC, VitaliSantalau commented on 06-events-practice/2-tooltip/index.js
> +      if (tooltip) {
функция обработчик сохранена => обработчик события может быть назначен и удален

2021-07-06 16:27 UTC, dosandk approved these changes
good 👍

2021-07-06 16:27 UTC, merged